# Generated by Django 6.0.1 on 2026-01-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Champion',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('puuid', models.CharField(blank=True, max_length=255, null=True)),
                ('soloq', models.CharField(blank=True, max_length=255, null=True)),
                ('flexq', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('type_game', models.CharField(blank=True, max_length=255, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('kill', models.IntegerField(blank=True, null=True)),
                ('death', models.IntegerField(blank=True, null=True)),
                ('assist', models.IntegerField(blank=True, null=True)),
                ('total_team_kill', models.IntegerField(blank=True, null=True)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entity.champion')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entity.player')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('BOTTOM', 'Bottom'), ('SUPPORT', 'Support'), ('SUB', 'Sub')], max_length=255)),
                ('isSub', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Entity.player')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Entity.team')),
            ],
            options={
                'db_table': 'TeamPlayer',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Entity.user'),
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=255)),
                ('teamOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_team_one', to='Entity.team')),
                ('teamTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_team_two', to='Entity.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.user')),
            ],
            options={
                'db_table': 'Matchup',
            },
        ),
    ]
